name: Linux image build

on:
  push:
    paths:
      - "docker/linux/**"
  schedule:
    - cron: "0 5 * * 6"
  workflow_dispatch:

jobs:
  build-base:
    runs-on: ubuntu-18.04
    steps:
      - name: Registry login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: actions/checkout@master

      - name: Build and push Linux base images
        working-directory: docker
        run: |
          docker-compose -f docker-compose-linux.yml build 
          docker-compose -f docker-compose-linux.yml push