name: Linux section 05 image build

on:
  push:
    paths:
      - "app/05/05-03/**"
  schedule:
    - cron: "0 4 * * 6"
  workflow_dispatch:

jobs:
  section-05:
    runs-on: ubuntu-18.04
    steps:
      - name: Registry login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: actions/checkout@master

      - name: Build and push section 05 app images
        working-directory: app/05/05-03/build
        run: |
          docker-compose -f docker-compose-linux.yml build 
          docker-compose -f docker-compose-linux.yml push
