name: Windows section 05 image build

on:
  push:
    paths:
      - "app/05/05-03/**"
  schedule:
    - cron: "0 3 * * 6"
  workflow_dispatch:

jobs:
  section-05:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@master
      - name: Build and push section 05 Windows images
        working-directory: app/05/05-03/build
        run: |
          docker login -u $env:USER -p $env:TOKEN
          docker-compose -f docker-compose-windows.yml build 
          docker-compose -f docker-compose-windows.yml push
        env:
          USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
